export interface RedemittelQuestion {
  id: string;
  topic: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export const redemittelQuestions: RedemittelQuestion[] = [
  {
    id: "r1",
    topic: "Telefonieren",
    question: "Wie beginnen Sie ein geschäftliches Telefonat höflich?",
    options: [
      "Hey, hier ist Max. Was geht?",
      "Guten Tag, hier spricht Max Müller von der Logistik GmbH.",
      "Ich bin Max. Verbinden Sie mich.",
    ],
    correctIndex: 1,
    explanation: "Geschäftliche Anrufe beginnen mit einer höflichen Vorstellung inklusive Firma.",
  },
  {
    id: "r2",
    topic: "Beschwerden",
    question: "Welche Redewendung passt zu einer sachlichen Beschwerde?",
    options: [
      "Das ist ja unglaublich!",
      "Leider muss ich mich über die verspätete Lieferung beschweren.",
      "Ich will sofort mein Geld zurück!",
    ],
    correctIndex: 1,
    explanation: "Beschwerden sollten sachlich und höflich formuliert werden.",
  },
  {
    id: "r3",
    topic: "Termine",
    question: "Wie schlagen Sie einen Termin höflich vor?",
    options: [
      "Morgen um 10 Uhr. Punkt.",
      "Passt es Ihnen am Mittwoch um 14 Uhr?",
      "Sie müssen morgen kommen.",
    ],
    correctIndex: 1,
    explanation: "Eine Frageform mit 'Passt es Ihnen ...' ist höflich.",
  },
  {
    id: "r4",
    topic: "Meetings",
    question: "Wie bringen Sie Ihre Meinung in einer Besprechung ein?",
    options: [
      "Das ist doch total falsch!",
      "Ich bin der Meinung, dass wir das noch einmal prüfen sollten.",
      "Keiner hat mich gefragt.",
    ],
    correctIndex: 1,
    explanation: "'Ich bin der Meinung, dass ...' ist eine höfliche Art, einen Standpunkt zu äußern.",
  },
  {
    id: "r5",
    topic: "E-Mails",
    question: "Welche Anrede ist in einer formellen E-Mail korrekt?",
    options: [
      "Lieber Chef,",
      "Sehr geehrte Damen und Herren,",
      "Hallo zusammen,",
    ],
    correctIndex: 1,
    explanation: "'Sehr geehrte Damen und Herren' ist die Standard-Anrede in formeller Korrespondenz.",
  },
  {
    id: "r6",
    topic: "Konflikte",
    question: "Wie sprechen Sie ein Problem konstruktiv an?",
    options: [
      "Sie machen das immer falsch!",
      "Ich habe das Gefühl, dass die Termine in letzter Zeit nicht eingehalten werden.",
      "Das ist nicht mein Problem.",
    ],
    correctIndex: 1,
    explanation: "'Ich habe das Gefühl, dass ...' nimmt das Problem sachlich und ohne Schuldzuweisung an.",
  },
  {
    id: "r7",
    topic: "Bewerbungsgespräch",
    question: "Wie formulieren Sie Ihre Stärken überzeugend?",
    options: [
      "Ich bin der Beste.",
      "Meine Stärken sind Teamfähigkeit und Zuverlässigkeit.",
      "Ich habe keine Stärken.",
    ],
    correctIndex: 1,
    explanation: "Konkrete Stärken nennen wirkt professioneller als Pauschalurteile.",
  },
  {
    id: "r8",
    topic: "Meinung äußern",
    question: "Wie leiten Sie eine differenzierte Meinung ein?",
    options: [
      "Einerseits bietet Homeoffice Flexibilität, andererseits fehlt der Austausch.",
      "Homeoffice ist gut. Ende der Diskussion.",
      "Ich weiß nicht.",
    ],
    correctIndex: 0,
    explanation: "'Einerseits ... andererseits' zeigt eine differenzierte Betrachtung.",
  },
  {
    id: "r9",
    topic: "Informationen zusammenfassen",
    question: "Wie fassen Sie Informationen sachlich zusammen?",
    options: [
      "Also irgendwie war da was.",
      "Zusammenfassend lässt sich sagen, dass ...",
      "Keine Ahnung, was wichtig war.",
    ],
    correctIndex: 1,
    explanation: "'Zusammenfassend lässt sich sagen, dass ...' ist ein passendes Redemittel.",
  },
  {
    id: "r10",
    topic: "Konsens finden",
    question: "Wie schlagen Sie einen Kompromiss vor?",
    options: [
      "Lassen Sie uns eine Zwischenlösung finden.",
      "Ich gebe nicht nach.",
      "Machen Sie, was Sie wollen.",
    ],
    correctIndex: 0,
    explanation: "'Lassen Sie uns eine Zwischenlösung finden' ist konstruktiv und lösungsorientiert.",
  },
  {
    id: "r11",
    topic: "Zusagen",
    question: "Wie bestätigen Sie eine Vereinbarung höflich?",
    options: [
      "Ja, das passt. Vielen Dank.",
      "Vielleicht.",
      "Ich weiß nicht.",
    ],
    correctIndex: 0,
    explanation: "Eine klare, höfliche Zusage ist professionell und verbindlich.",
  },
  {
    id: "r12",
    topic: "Ablehnen",
    question: "Wie lehnen Sie einen Termin höflich ab?",
    options: [
      "Leider passt mir der Termin nicht. Gibt es eine Alternative?",
      "Nein.",
      "Ich habe keine Zeit.",
    ],
    correctIndex: 0,
    explanation: "Begründung und Alternativvorschlag machen die Absage höflicher.",
  },
  {
    id: "r13",
    topic: "Nachfragen",
    question: "Wie fragen Sie höflich nach einer Information?",
    options: [
      "Könnten Sie mir das bitte noch einmal erklären?",
      "Was?",
      "Ich verstehe nichts.",
    ],
    correctIndex: 0,
    explanation: "'Könnten Sie ...' ist höflich und professionell.",
  },
  {
    id: "r14",
    topic: "Telefonieren",
    question: "Wie verabschieden Sie sich am Telefon höflich?",
    options: [
      "Auf Wiederhören und einen schönen Tag noch.",
      "Tschüss.",
      "Ich lege auf.",
    ],
    correctIndex: 0,
    explanation: "'Auf Wiederhören' ist die geschäftliche Verabschiedung am Telefon.",
  },
  {
    id: "r15",
    topic: "Zustimmen",
    question: "Wie drücken Sie Ihre Zustimmung in einer Besprechung aus?",
    options: [
      "Damit bin ich vollkommen einverstanden.",
      "Das interessiert mich nicht.",
      "Ich habe keine Meinung dazu.",
    ],
    correctIndex: 0,
    explanation: "'Damit bin ich vollkommen einverstanden' ist eine klare, höfliche Zustimmung.",
  },
  {
    id: "r16",
    topic: "Widersprechen",
    question: "Wie widersprechen Sie sachlich und höflich?",
    options: [
      "Das sehe ich anders, weil ...",
      "Das ist doch Quatsch!",
      "Sie verstehen das nicht.",
    ],
    correctIndex: 0,
    explanation: "'Das sehe ich anders, weil ...' leitet einen sachlichen Widerspruch ein.",
  },
  {
    id: "r17",
    topic: "Vorschlagen",
    question: "Wie machen Sie einen konstruktiven Vorschlag?",
    options: [
      "Wie wäre es, wenn wir das nächste Woche besprechen?",
      "Wir machen das so.",
      "Ich will das anders machen.",
    ],
    correctIndex: 0,
    explanation: "'Wie wäre es, wenn ...' ist ein höflicher Vorschlag.",
  },
  {
    id: "r18",
    topic: "Hilfe bitten",
    question: "Wie bitten Sie einen Kollegen um Unterstützung?",
    options: [
      "Könnten Sie mir bitte kurz helfen?",
      "Mach das für mich!",
      "Ich komme nicht weiter, egal.",
    ],
    correctIndex: 0,
    explanation: "'Könnten Sie mir bitte kurz helfen' ist höflich und direkt.",
  },
  {
    id: "r19",
    topic: "Entschuldigen",
    question: "Wie entschuldigen Sie sich für ein Versäumnis?",
    options: [
      "Es tut mir leid, dass ich den Termin verpasst habe.",
      "Das ist nicht meine Schuld.",
      "Passiert halt.",
    ],
    correctIndex: 0,
    explanation: "Eine ehrliche Entschuldigung mit konkretem Versäumnis wirkt professionell.",
  },
  {
    id: "r20",
    topic: "Glückwünsche",
    question: "Wie gratulieren Sie einem Kollegen zur Beförderung?",
    options: [
      "Herzlichen Glückwunsch zur Beförderung!",
      "Na endlich.",
      "Wusste ich doch, dass ich es besser gemacht hätte.",
    ],
    correctIndex: 0,
    explanation: "'Herzlichen Glückwunsch' ist die passende Gratulation.",
  },
  {
    id: "r21",
    topic: "Einwände äußern",
    question: "Wie äußern Sie einen Einwand in einer Diskussion?",
    options: [
      "Ich habe jedoch Bedenken, was die Kosten betrifft.",
      "Das geht gar nicht!",
      "Das ist doch alles falsch.",
    ],
    correctIndex: 0,
    explanation: "'Ich habe jedoch Bedenken' ist eine sachliche Art, Einwände zu formulieren.",
  },
  {
    id: "r22",
    topic: "Informationen zusammenfassen",
    question: "Wie leiten Sie ein Fazit ein?",
    options: [
      "Alles in allem lässt sich sagen, dass ...",
      "Und so weiter.",
      "Ich habe keine Ahnung.",
    ],
    correctIndex: 0,
    explanation: "'Alles in allem lässt sich sagen' ist ein passendes Fazit-Redemittel.",
  },
  {
    id: "r23",
    topic: "Vermutungen",
    question: "Wie drücken Sie eine vorsichtige Vermutung aus?",
    options: [
      "Es könnte sein, dass der Termin verschoben wird.",
      "Der Termin wird definitiv verschoben.",
      "Ich weiß es nicht genau, aber egal.",
    ],
    correctIndex: 0,
    explanation: "'Es könnte sein, dass ...' drückt eine vorsichtige Vermutung aus.",
  },
  {
    id: "r24",
    topic: "Bedauern",
    question: "Wie drücken Sie Bedauern aus?",
    options: [
      "Das bedaure ich sehr.",
      "Schade, aber egal.",
      "Das ist nicht mein Problem.",
    ],
    correctIndex: 0,
    explanation: "'Das bedaure ich sehr' ist formell und ausdrucksstark.",
  },
  {
    id: "r25",
    topic: "Einladen",
    question: "Wie laden Sie jemanden höflich zu einem Meeting ein?",
    options: [
      "Darf ich Sie zu unserer Besprechung einladen?",
      "Kommen Sie zur Besprechung.",
      "Sie müssen kommen.",
    ],
    correctIndex: 0,
    explanation: "'Darf ich Sie einladen' ist eine höfliche Einladung.",
  },
  {
    id: "r26",
    topic: "Aufforderungen",
    question: "Wie fordern Sie höflich zur Mitarbeit auf?",
    options: [
      "Wären Sie so freundlich, mir Ihre Unterlagen zuzuschicken?",
      "Schicken Sie mir die Unterlagen!",
      "Ich brauche Ihre Unterlagen jetzt.",
    ],
    correctIndex: 0,
    explanation: "'Wären Sie so freundlich' macht eine Aufforderung sehr höflich.",
  },
  {
    id: "r27",
    topic: "Kritik üben",
    question: "Wie üben Sie Kritik konstruktiv?",
    options: [
      "An dieser Stelle sehe ich noch Verbesserungspotenzial.",
      "Das haben Sie schlecht gemacht.",
      "Das gefällt mir überhaupt nicht.",
    ],
    correctIndex: 0,
    explanation: "'Verbesserungspotenzial' ist eine konstruktive Formulierung für Kritik.",
  },
  {
    id: "r28",
    topic: "Loben",
    question: "Wie loben Sie die Arbeit eines Kollegen?",
    options: [
      "Das haben Sie wirklich hervorragend gemacht.",
      "Nicht schlecht.",
      "Das war besser als erwartet.",
    ],
    correctIndex: 0,
    explanation: "'Wirklich hervorragend' ist ein ausdrucksstarkes Lob.",
  },
  {
    id: "r29",
    topic: "Rat geben",
    question: "Wie geben Sie jemandem einen höflichen Rat?",
    options: [
      "Ich würde Ihnen empfehlen, das frühzeitig zu klären.",
      "Sie sollten das sofort ändern.",
      "Machen Sie das nicht so dumm.",
    ],
    correctIndex: 0,
    explanation: "'Ich würde Ihnen empfehlen' ist eine höfliche Rat-Formulierung.",
  },
  {
    id: "r30",
    topic: "Bestätigen",
    question: "Wie bestätigen Sie den Erhalt einer E-Mail?",
    options: [
      "Vielen Dank für Ihre Nachricht. Ich bestätige den Erhalt.",
      "Ich habe Ihre Mail bekommen.",
      "Okay.",
    ],
    correctIndex: 0,
    explanation: "Eine formelle Empfangsbestätigung wirkt professionell.",
  },
  {
    id: "r31",
    topic: "Ablehnen",
    question: "Wie lehnen Sie ein Angebot höflich ab?",
    options: [
      "Nein, das will ich nicht.",
      "Vielen Dank, aber ich muss das Angebot leider ablehnen.",
      "Das interessiert mich nicht.",
    ],
    correctIndex: 1,
    explanation: "'Vielen Dank, aber ...' ist eine höfliche Ablehnung.",
  },
  {
    id: "r32",
    topic: "Zusagen",
    question: "Wie sagen Sie zu einem Termin zu?",
    options: [
      "Ja, das passt mir.",
      "Gerne, ich bestätige den Termin am Dienstag um 14 Uhr.",
      "Okay, warum nicht.",
    ],
    correctIndex: 1,
    explanation: "Eine formelle Zusage bestätigt Tag und Uhrzeit noch einmal.",
  },
  {
    id: "r33",
    topic: "Nachfragen",
    question: "Wie fragen Sie höflich nach einem Sachverhalt?",
    options: [
      "Was soll das jetzt?",
      "Darf ich Sie bitten, mir das noch einmal zu erklären?",
      "Ich verstehe das nicht.",
    ],
    correctIndex: 1,
    explanation: "'Darf ich Sie bitten' macht die Nachfrage höflich.",
  },
  {
    id: "r34",
    topic: "Termin verschieben",
    question: "Wie bitten Sie um Terminverschiebung?",
    options: [
      "Ich komme morgen nicht.",
      "Leider muss ich unseren Termin auf einen späteren Zeitpunkt verschieben.",
      "Der Termin ist blöd.",
    ],
    correctIndex: 1,
    explanation: "Eine begründete Bitte um Verschiebung ist professionell.",
  },
  {
    id: "r35",
    topic: "Entschuldigung",
    question: "Wie entschuldigen Sie sich formell?",
    options: [
      "Tut mir leid.",
      "Ich entschuldige mich für die entstandenen Unannehmlichkeiten.",
      "Das war nicht meine Schuld.",
    ],
    correctIndex: 1,
    explanation: "'Ich entschuldige mich für ...' ist eine formelle Entschuldigung.",
  },
  {
    id: "r36",
    topic: "Begrüßung",
    question: "Wie begrüßen Sie Gäste oder Kunden höflich?",
    options: [
      "Na, hallo.",
      "Herzlich willkommen. Wie kann ich Ihnen behilflich sein?",
      "Was wollen Sie?",
    ],
    correctIndex: 1,
    explanation: "'Herzlich willkommen' und ein Hilfsangebot wirken einladend.",
  },
  {
    id: "r37",
    topic: "Telefonat beenden",
    question: "Wie beenden Sie ein geschäftliches Telefonat höflich?",
    options: [
      "Ich leg auf.",
      "Vielen Dank für das Gespräch. Auf Wiederhören.",
      "Tschüss.",
    ],
    correctIndex: 1,
    explanation: "'Vielen Dank für das Gespräch' und 'Auf Wiederhören' sind passend.",
  },
  {
    id: "r38",
    topic: "Smalltalk",
    question: "Welche Frage eignet sich für Smalltalk am Arbeitsplatz?",
    options: [
      "Wie viel verdienen Sie?",
      "Hatten Sie ein schönes Wochenende?",
      "Warum sind Sie geschieden?",
    ],
    correctIndex: 1,
    explanation: "Ein unverfängliches Thema wie das Wochenende eignet sich für Smalltalk.",
  },
  {
    id: "r39",
    topic: "Präsentation",
    question: "Wie beginnen Sie eine berufliche Präsentation?",
    options: [
      "Also, ich fange jetzt mal an.",
      "Guten Tag, ich freue mich, Ihnen heute unser Konzept vorzustellen.",
      "Hört mir jetzt alle zu.",
    ],
    correctIndex: 1,
    explanation: "Eine klare Begrüßung und Vorstellung des Themas eröffnet eine Präsentation.",
  },
  {
    id: "r40",
    topic: "Zustimmung",
    question: "Wie drücken Sie Zustimmung aus?",
    options: [
      "Das sehe ich genauso.",
      "Das ist mir egal.",
      "Ich habe keine Meinung dazu.",
    ],
    correctIndex: 0,
    explanation: "'Das sehe ich genauso' drückt eindeutige Zustimmung aus.",
  },
  {
    id: "r41",
    topic: "Widerspruch",
    question: "Wie widersprechen Sie höflich?",
    options: [
      "Das ist doch Quatsch!",
      "Das verstehe ich anders. Meiner Meinung nach ...",
      "Sie haben keine Ahnung.",
    ],
    correctIndex: 1,
    explanation: "'Das verstehe ich anders' ist ein höflicher Einstieg für Widerspruch.",
  },
  {
    id: "r42",
    topic: "Vorschlagen",
    question: "Wie machen Sie einen Vorschlag im Team?",
    options: [
      "Wir machen es so, wie ich gesagt habe.",
      "Wie wäre es, wenn wir das Projekt in zwei Phasen aufteilen?",
      "Ihr müsst das ändern.",
    ],
    correctIndex: 1,
    explanation: "'Wie wäre es, wenn ...' ist eine konstruktive Vorschlagsformulierung.",
  },
  {
    id: "r43",
    topic: "Erklärung bitten",
    question: "Wie bitten Sie um eine Erklärung?",
    options: [
      "Erklären Sie das mal!",
      "Könnten Sie mir bitte erklären, wie das funktioniert?",
      "Ich verstehe das sowieso nicht.",
    ],
    correctIndex: 1,
    explanation: "'Könnten Sie mir bitte erklären' ist höflich und klar.",
  },
  {
    id: "r44",
    topic: "Bedauern",
    question: "Wie drücken Sie Bedauern aus?",
    options: [
      "Das ist doch egal.",
      "Es tut mir leid, dass es so gekommen ist.",
      "Schade, aber nicht mein Problem.",
    ],
    correctIndex: 1,
    explanation: "'Es tut mir leid, dass ...' drückt aufrichtiges Bedauern aus.",
  },
  {
    id: "r45",
    topic: "Hoffnung",
    question: "Wie drücken Sie Hoffnung aus?",
    options: [
      "Hoffentlich klappt es.",
      "Ich hoffe sehr, dass wir eine gemeinsame Lösung finden.",
      "Mal sehen, was passiert.",
    ],
    correctIndex: 1,
    explanation: "'Ich hoffe sehr, dass ...' ist eine formelle Hoffnungsäußerung.",
  },
  {
    id: "r46",
    topic: "Empfehlung",
    question: "Wie sprechen Sie eine Empfehlung aus?",
    options: [
      "Kaufen Sie das einfach.",
      "Ich kann Ihnen dieses Produkt wärmstens empfehlen.",
      "Das müssen Sie nehmen.",
    ],
    correctIndex: 1,
    explanation: "'Ich kann Ihnen wärmstens empfehlen' ist eine höfliche Empfehlung.",
  },
  {
    id: "r47",
    topic: "Entscheidung mitteilen",
    question: "Wie teilen Sie eine Entscheidung mit?",
    options: [
      "Wir haben uns entschieden.",
      "Nach sorgfältiger Prüfung haben wir uns für Variante B entschieden.",
      "Es wird Variante B geben.",
    ],
    correctIndex: 1,
    explanation: "'Nach sorgfältiger Prüfung' macht die Entscheidungung nachvollziehbar.",
  },
  {
    id: "r48",
    topic: "Rückfrage",
    question: "Wie stellen Sie eine Rückfrage zu einem unklaren Punkt?",
    options: [
      "Das ist doch klar!",
      "Entschuldigung, aber ich möchte noch einmal nachfragen: Meinen Sie ...?",
      "Ich habe das nicht verstanden, wiederholen Sie.",
    ],
    correctIndex: 1,
    explanation: "'Entschuldigung, ich möchte noch einmal nachfragen' ist höflich und präzise.",
  },
  {
    id: "r49",
    topic: "Geduld bitten",
    question: "Wie bitten Sie um Geduld?",
    options: [
      "Warten Sie halt.",
      "Bitte haben Sie noch einen Moment Geduld. Ich prüfe das sofort.",
      "Das dauert jetzt.",
    ],
    correctIndex: 1,
    explanation: "'Bitte haben Sie noch einen Moment Geduld' ist höflich und beruhigend.",
  },
  {
    id: "r50",
    topic: "Danken",
    question: "Wie danken Sie in einer formellen E-Mail?",
    options: [
      "Danke.",
      "Ich bedanke mich herzlich für Ihre Unterstützung.",
      "Ciao und danke.",
    ],
    correctIndex: 1,
    explanation: "'Ich bedanke mich herzlich für ...' ist eine formelle Danksagung.",
  },
];
